<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Carlens.AiWorker-62f2d375-b7bc-4cf0-8bc1-a896f952bd7d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="1.6.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Carlens.Application\Carlens.Application.csproj" />
    <ProjectReference Include="..\Carlens.Infrastructure\Carlens.Infrastructure.csproj" />
    <ProjectReference Include="..\Carlens.Contracts\Carlens.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Carlens.Tests" />
  </ItemGroup>
</Project>
