<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Carlens.Contracts\Carlens.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7bb31c50-1fd6-4f55-b59e-9a6cc3d801ec</UserSecretsId>
  </PropertyGroup>

</Project>
